title: Emma Hicks
logo:
description: Data Administrator  |  MBCS |  Neurodivergent (Autism Spectrum Condition / Dyslexia)  |  Open to new opportunities
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
